### ISSUE TITLE
Error while attempting to load fluid crafting+other mods

### ISSUE THREAD

**Issue by Delfite** [phantamanta44/ae2-fluid-crafting#1]
VanillaFix detected a conflict between your mod and another mod causing a Hard-crash, if I were to guess it might be Traveller's Backpack which is a bit odd considering it doesn't use fluid crafting, please get this fixed ASAP as I would like to use it in a personal pack I'm making and this would be an amazing Q.O.L. mod

Report: https://pastebin.com/6bw1zVHH

"Note to self: Don't try to mix it..."
-Sauce

**Comment by phantamanta44** [comment]
did this crash happen right as you exited a world/server?

**Comment by phantamanta44** [comment]
i think this is an issue with traveler's backpack and it should be fixed in Tiviacz1337/Travelers-Backpack@d144164e85dc61c2071ee8f8ff44a85ce8b44190; i suggest trying out the latest build there and seeing if this issue persists.

**Comment by Delfite** [comment]
To answer your first question, No my game crashed right after all the mods had been loaded. VanillaFix detected a conflict that was too severe to continue playing the game PERIOD.

**Comment by phantamanta44** [comment]
is this still an ongoing issue?

**Comment by Delfite** [comment]
Haven't checked yet, been figuring out some other issues since it would seem my pack has a lot more bugs than a normal pack which is kinda strange. I'll test it in a sec if my internet would behave for 5 seconds and let me download shit, I'll have an answer to you in a few minutes so expect another reply soon.
Edit: Grammar

**Comment by Delfite** [comment]
I am currently unsure as to if the problem still persists as this crash was caused by "Advanced Machines" by Chocohead. Someone commented a patch for this so I will be testing that to see if that works, I'll update you on this in a little bit.

**Comment by Delfite** [comment]
"Good news everyone! My ship hasn't been completely destroyed yet!" -Farnzworth
Yay, the modpack doesn't crash anymore, woohoo!
