### ISSUE TITLE
Me Fluid Pattern Terminal - Unable to change sorting method

### ISSUE THREAD

**Issue by Zelda-Swordsman** [phantamanta44/ae2-fluid-crafting#12]
I am playing on a singleplayer world using the Dungeons Dragons & Space Shuttles 8.0_R1 and these additional mods:

Ae2 Fluid Crafting 1.0.9
Ae2 Stuff 0.7.0.4
Flux Networks 4.0.15-32

When clicking on the sort by button in the Fluid Pattern Terminal to change the sorting method, the icon will update upon one click without affecting the sorting of items in the terminal, with any further clicking resulting in the icon to return to the AZ sorting icon. Clicking rapidly causes the sort by mod icon to appear for a split second. Exiting and reentering the terminal causes the icon to revert back to the AZ sorting icon if on the sort by number of items icon.

Upon further testing the View and Sort Order buttons function in much the same way, failing to change how items are sorted.

![Me Fluid Pattern Terminal](https://user-images.githubusercontent.com/36285521/106789278-10b1b380-6620-11eb-9451-ae622058f72b.png)
Me Fluid Pattern Terminal

![ME Crafting Terminal](https://user-images.githubusercontent.com/36285521/106789284-11e2e080-6620-11eb-8245-1dcc130293eb.png)
Me Crafting Terminal for Reference

**Comment by phantamanta44** [comment]
[AE2FC 1.0.10](https://www.curseforge.com/minecraft/mc-mods/ae2-fluid-crafting/files/3254163) is now published and should address this issue
