### ISSUE TITLE
ME level maintainer produce drops items can't be automatically turned into fluid

### ISSUE THREAD

**Issue by kuainx** [phantamanta44/ae2-fluid-crafting#13]
I want to use ME level maintainer from lazyae2 to maintain the quantity of fluid.

crafting: 1 ingot -> 144mB fluid
1.set the level maintainer to maintain 144 drops
2.the crafting finished, got 144mB of fluid, and 144 drops (the ME terminal shows 288drops)
3.the 144mB fluid can be used as normal fluid
4.these 144drops can't be removed from ME fluid interface, but can be used as crafting materials
5.if I remove the drops from the ME terminal and then inserted it , I got extra fluid!
6.after do (3) more times, I can get real 288mB fluid

I want to output fluid from fluid interface, but if it produce drop items which can't be removed from fluid interface or turned into fluid , it will stop producing fluid soon.
I'm sorry my English is not good, but I really want to maintain the fluid amount easily like items, THANKS!!!

all mods
![20210225170534](https://user-images.githubusercontent.com/22209650/109129539-b5d92b00-778b-11eb-9cb0-4c73ecb1001c.png)

ME network
![2021-02-25_17 03 53](https://user-images.githubusercontent.com/22209650/109129635-cf7a7280-778b-11eb-8001-b1f9997bcb59.png)

![2021-02-25_17 00 06](https://user-images.githubusercontent.com/22209650/109132042-5fb9b700-778e-11eb-8e45-0cfa8d4827ab.png)
![2021-02-25_17 00 11](https://user-images.githubusercontent.com/22209650/109132066-63e5d480-778e-11eb-9ad7-9930a9bede99.png)
![2021-02-25_17 00 17](https://user-images.githubusercontent.com/22209650/109132086-67795b80-778e-11eb-85a4-b6f298e45dde.png)
![2021-02-25_17 01 04](https://user-images.githubusercontent.com/22209650/109132101-6a744c00-778e-11eb-9c4b-f6c00f430f21.png)

**Comment by dacioromero** [comment]
I ran into the same issue, a temporary fix I have is to have an interface which keeps the droplets in stock and then imports them back into the ME system

**Comment by phantamanta44** [comment]
sorry i haven't been active lately. i think i've worked out why this issue happens, and i have some ideas about how to fix it

**Comment by phantamanta44** [comment]
alright, this is addressed on the Lazy AE2 side by https://github.com/phantamanta44/Lazy-AE2/commit/2471accb484f3487f00ccd5746856f3c19a9fa1b

**Comment by phantamanta44** [comment]
[Lazy AE2 1.1.26](https://www.curseforge.com/minecraft/mc-mods/lazy-ae2/files/3254160) is now published
