### ISSUE TITLE
Fluid Discretizer does not show up on network tool

### ISSUE THREAD

**Issue by milkev** [phantamanta44/ae2-fluid-crafting#16]
**What I want**
Fluid Discretizer to show up when using the me network tool.

**Why I want this**
the network tool is a quick way to see whats connected to your network. its especially useful if you are building a large base that has lots of automation.
i spent the better part of this afternoon trying to figure out why my network was producing a fake double of all my droplets... only to find out i had placed a second one, since it didnt show up on my network tool, i had assumed i hadnt placed one yet... but already had one placed in a far off corner of my base.

**Potential alternate solution**
only provide the effects of a single discretizer, even if multiple discretizers are attached to the network.

**Comment by phantamanta44** [comment]
should be fixed in d9656ffae29383d64e0061353c0b81c600ac1993. it's indended for multiple discretizers to stack their effects, since they're supposed to be self-contained devices
