### ISSUE TITLE
Crafted fluids are not recognized as 'crafted'

### ISSUE THREAD

**Issue by milkev** [phantamanta44/ae2-fluid-crafting#17]
when crafting a fluid (via melting or other methods) the me system does not register that it has been crafted, even though the fluid was put into the system. this has been resulting in me having to cancel and re-initialize any recipes that start 

my settup is pushing the fluids directly from the melter into a double interface, and they are stored in my me system as a fluid, to which a discretizer is attached. the storage and discretizer are on a storage subsystem, if that makes a difference (it shouldnt)

how to reproduce:
create recipe to turn a metal into a fluid/drops
use recipe
watch me system fill with fluid/drops
watch autocraft not register as completed

**Comment by milkev** [comment]
FIX:
placing fluid discretizer in a storage subsystem rather than the main system causes this issue. if possible, a fix would be appreciated. for now, the easy method is simply to move the discretizer to the main system.

**Comment by phantamanta44** [comment]
i'm not sure this is a bug. the fluid discretizer acts similarly to a crafting cpu in the way it consumes crafting results, so it makes sense that it can't be placed on a subnet and still work for autocrafting, the same way the crafting cpu can't

**Comment by milkev** [comment]
that would make sense!
thanks for your explanation
