### ISSUE TITLE
Server crush on NoClassDefFoundError: net/minecraft/client/resources/I18n

### ISSUE THREAD

**Issue by Krutoy242** [phantamanta44/ae2-fluid-crafting#2]
I tested mod on client and everything was fine. But trying to lunch server with new mod crushing on load with error:
```java
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at xyz.phanta.ae2fc.item.ItemFluidDrop.func_77653_i(ItemFluidDrop.java:40)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:617)
```
Version: ae2fc-1.12.2-1.0.4

[crash-2020-06-25_11.25.41-server.txt](https://gist.github.com/Krutoy242/9628cb3818cf67be74bbcaed9eafa62a)

**Comment by phantamanta44** [comment]
well, that's a little annoying

**Comment by phantamanta44** [comment]
this version should fix it: https://www.curseforge.com/minecraft/mc-mods/ae2-fluid-crafting/files/2988465
