### ISSUE TITLE
Critical issue - fluid and drops quantities information is bugged

### ISSUE THREAD

**Issue by IGalat** [phantamanta44/ae2-fluid-crafting#24]
Hi.
Using this mod with Omnifactory, 1.12.2 mc.

The bug is present only for display - you can't pull more than there is (so no duping), but this affects level emitters/maintainers, as well as shows wrong numbers in terminals.

Cases:
1. Connect Discredizer. Use ME drive or chest(this is better for testing, as you can see actual amount); put some fluid in it, say 1B water. You'll see correct numbers on both fluid terminal and regular. Now dis-and-reconnect Discredizer. You'll see 2B in fluid terminal (also 2B for any checks like level emitters), or 2k drops, or both.
2. Set up drum with import and export fluid buses, on water. Watch drops number go crazy - it doesn't seem to go down and only up.
3. Set up ME toggle bus with inverted timer, and discredizer on it (I thought this would be my workaround: the drops number would reset, and 2x displayed fluid I'd just accept as a thing; I could work with that). 
Now fluid level will be x2(or not even? might be correct now), but drops number, although will "reset" on disconnect of Discredizer, will not reset to 0; you'll have 24(I think) per bucket that went out! (If you disconnect the Discredizer, it will not disappear. I tested this with only storage being a single fluid storage cell - so having drops in AE inv was not possible)
And when Discredizer does reconnect, it shows incorrect number of drops again. With 6B water cycling back and forth between a drum and ME system, it has shown 16k on reconnect, and number going up (I think by a correct amount - 1k for 1 bucket) until it disconnected again(was showing some 100ish drops for a couple of ticks), and 16k on reconnect again.

This is mostly bad for automation, which is kinda the whole point :)

**Comment by phantamanta44** [comment]
omnifactory uses PAE2. can you try replacing it with vanilla AE2 and check to see if the issue persists?

**Comment by IGalat** [comment]
Yeah, with vanilla AE2 works fine.

**Comment by IGalat** [comment]
Do you know if maybe a tweak in the code could circumvent this? I tried disabling the cache for discredizer inventory getAvailableItems, but no dice
