### ISSUE TITLE
One slot can accept only up to 127mb of fluid

### ISSUE THREAD

**Issue by ShadelessFox** [phantamanta44/ae2-fluid-crafting#3]
When encoding pattern inside Fluid Pattern Encoder each slot can accept only up to 127mb of fluid making patterns with more than (potentially, 9*127mb) 1143mb of fluid impossible.
At mod's page on curseforge I can see you are encoding with 500mb of fluid, so I'm a bit confused, maybe I'm doing something wrong.

![Image](https://i.imgur.com/vMsf2it.gif)

**Comment by phantamanta44** [comment]
when i try encoding a pattern with TiCl4 in the gregtech tanks, i'm able to encode larger patterns. does this only happen with enderio tanks? does the jei integration allow you to encode larger patterns? also, a list of all installed mods might be helpful

**Comment by ShadelessFox** [comment]
It's Omnifactory. Vanilla buckets (even with water) also doesn't work, JEI integration don't work either, fluids just not showing upon inserting pattern (pressing '+' on craft) ¯\_(ツ)_/¯

**Comment by phantamanta44** [comment]
that's... really weird. i'll investigate

**Comment by phantamanta44** [comment]
i've just installed omnifactory 1.2.2 and the fluid pattern encoder seems to function perfectly fine. have you added any additional mods besides ae2fc?

**Comment by phantamanta44** [comment]
ah, never mind; it only occurs when connected to a server and i was testing on single-player

**Comment by phantamanta44** [comment]
should be fixed in 1.0.6: https://www.curseforge.com/minecraft/mc-mods/ae2-fluid-crafting/files/2990001

**Comment by ShadelessFox** [comment]
I was sleeping, ha-ha :D
Thank you for investigating!
