### ISSUE TITLE
Me fluid discretizer destroy automatically when connected to network

### ISSUE THREAD

**Issue by programgames** [phantamanta44/ae2-fluid-crafting#4]
Hello , I wanted to try this mod and when i connect the Me fluid discretizer , the block got automatically destroyed like this : https://gyazo.com/bad9afc8798ae21ac279f30d7dc07c57

**Comment by phantamanta44** [comment]
do you have a security terminal on the network?

**Comment by phantamanta44** [comment]
should be fixed in 1.0.6: https://www.curseforge.com/minecraft/mc-mods/ae2-fluid-crafting/files/2990001
