### ISSUE TITLE
Fluids are not being imported upon inserting craft from GregTech's assembler

### ISSUE THREAD

**Issue by ShadelessFox** [phantamanta44/ae2-fluid-crafting#5]
Still playing on Omnifactory. No mods were added since last issue. Using 1.0.6 version.

![Image](https://i.imgur.com/2dQ0t9V.gif)

**Comment by phantamanta44** [comment]
bleh, it looks like this is happening because the assembler has more than nine input slots. i'll see if i can work something out

**Comment by phantamanta44** [comment]
i don't like this solution much because it won't be able to handle recipes with > 9 inputs, but it'll work for now
