### ISSUE TITLE
issue with the ME Fluid Discretizer

### ISSUE THREAD

**Issue by zyt20001205** [phantamanta44/ae2-fluid-crafting#6]
ME Fluid Discretizer doesn‘t convert all fluids in my system into drops.
![F1C8F8D1-B155-4021-91D7-BE8D9A145E8A](https://user-images.githubusercontent.com/26330271/95646562-39a3bb00-0afc-11eb-9f7c-f273f6acc2ed.jpeg)
![C373052A-B3A3-4718-A4FA-788BF60155AF](https://user-images.githubusercontent.com/26330271/95646563-3d374200-0afc-11eb-8995-26476418beee.jpeg)

**Comment by phantamanta44** [comment]
that's pretty weird. i'll investigate when i have time

**Comment by phantamanta44** [comment]
may I ask exactly which fluids these are?

**Comment by zyt20001205** [comment]
Emm, I first enter the game. After the ae system is fully loaded, everything seems fine. Then I just keep the crafting terminal opened, some fluids start to disappear. These fluids are from Greg tech community edition.

**Comment by zyt20001205** [comment]
I’ve just taken two screen shots. The first one is fine, and the second one is abnormal.

**Comment by zyt20001205** [comment]
![Uploading 0ED74B01-3F4D-4912-8B14-FFBCA95D7444.png…]()

**Comment by zyt20001205** [comment]
![5F6A1A95-AA53-4091-85AB-D0FBBA97DE88](https://user-images.githubusercontent.com/26330271/95768555-1e49d300-0ce9-11eb-8b05-7ab3cc52ed4f.png)

**Comment by zyt20001205** [comment]
![Uploading AA604CAD-5490-4307-8BD8-1931B505BDE5.png…]()

**Comment by zyt20001205** [comment]
![EABA5264-81C3-440B-83BF-9C060520FDDA](https://user-images.githubusercontent.com/26330271/95768658-42a5af80-0ce9-11eb-9dca-2bfd06d8cc42.png)

**Comment by zyt20001205** [comment]
![Uploading EABA5264-81C3-440B-83BF-9C060520FDDA.png…]()

**Comment by zyt20001205** [comment]
![61CCB839-AC4A-4006-8582-B36A70D7E7BF](https://user-images.githubusercontent.com/26330271/95768720-5cdf8d80-0ce9-11eb-839b-56221aa47979.png)
![85AABBAE-6249-4A7C-B311-7335A8F93CD1](https://user-images.githubusercontent.com/26330271/95768726-60731480-0ce9-11eb-8000-f14f09367b6a.png)

**Comment by phantamanta44** [comment]
I suppose you have some processes running in the background that are moving the fluids around?

**Comment by zyt20001205** [comment]
nope...

**Comment by zyt20001205** [comment]
Even if so, there won’t be 20 kinds of fluids disappear at the same time.

**Comment by phantamanta44** [comment]
i can't seem to replicate this in a simple network that i just dumped 80 fluids into. can you describe the topology of your network? maybe draw a diagram

**Comment by zyt20001205** [comment]
I also build a simple network like this.
![Uploading AD09F89C-5506-4605-A175-58DA20D564B9.png…]()

**Comment by zyt20001205** [comment]
I also build a simple network like this.
![36B3C4FF-717C-42D5-A086-BE9D2F9B902B](https://user-images.githubusercontent.com/26330271/95771625-fc068400-0ced-11eb-8f22-35eedc9b1379.png)
![FF6D2510-A85C-45A8-8141-825ECFC989B6](https://user-images.githubusercontent.com/26330271/95771636-fdd04780-0ced-11eb-8b3f-ca5775d7c9c3.png)

**Comment by zyt20001205** [comment]
But the variety doesn’t seem to match.
![F20815BC-21C9-433D-A990-DEDF8D20386B](https://user-images.githubusercontent.com/26330271/95771763-31ab6d00-0cee-11eb-9549-7e145133f678.png)
![0B603483-8C12-4182-B96B-AF6BCC3779B2](https://user-images.githubusercontent.com/26330271/95771771-353ef400-0cee-11eb-91e0-f008e00a1643.png)

**Comment by zyt20001205** [comment]
And 
![DCB082DF-3DF5-43FC-A938-B3663273DC97](https://user-images.githubusercontent.com/26330271/95771868-63243880-0cee-11eb-88fd-e7cc39dc2afa.png)
![35254C5F-2074-48F9-B4B8-DB2154FCEB05](https://user-images.githubusercontent.com/26330271/95771875-661f2900-0cee-11eb-9008-1f1d07e996b7.png)
![Uploading D2BB6B79-336C-41D6-9765-BDC2B9D8CDC5.png…]()


the order seems to be changing all the time, meaning the kinds of fluids which are converted is changing continuously.

**Comment by zyt20001205** [comment]
May it’s my poor computer to be blamed.

**Comment by phantamanta44** [comment]
that doesn't make any sense... my testing setup is more or less identical and it doesn't do anything like this. do you have any other weird AE2 addons installed?

**Comment by zyt20001205** [comment]
![C4479AB4-E3DE-4B29-98AB-74597642F573](https://user-images.githubusercontent.com/26330271/95772310-1db43b00-0cef-11eb-8dca-4a27a8df6474.png)
![2C47C189-11FE-4F6C-B48D-03CBB86CFB77](https://user-images.githubusercontent.com/26330271/95772319-20169500-0cef-11eb-918d-69a96ebe256b.png)
![8B8C02A6-56BE-40A7-87B7-768CEDA816BF](https://user-images.githubusercontent.com/26330271/95772324-21e05880-0cef-11eb-9672-ebf0c2824bfa.png)

**Comment by zyt20001205** [comment]
Ae2 extracells2 ae2stuff spatialIOcompact

**Comment by zyt20001205** [comment]
Maybe have sth. To do with packagedauto or vanilla fix

**Comment by phantamanta44** [comment]
i'm still unable to replicate this at all. i'll try testing with your entire modpack later, when i have more time

**Comment by zyt20001205** [comment]
Hello, sorry for bringing you so much trouble. After recalling what I’ve done before having this wired issue for a few days, I finally memorize that I’ve changed my Java to adoptopenjdk as my initialization configuration to reduce memory allocate. After shifting back to Java, this issue doesn’t happen anymore. Again, sorry for wasting your time. Thank you for your patience and good work of modding, have a nice day!!!

**Comment by phantamanta44** [comment]
hey, thanks for taking the time to work out the issue
