### ISSUE TITLE
Enhancement require

### ISSUE THREAD

**Issue by Yefancy** [phantamanta44/ae2-fluid-crafting#8]
I have to say this is an amazing mod. Great for automating when I play GT or something like that. 

If the fluid output can be fed into the AE network from the ME interface (like Volumetric Flask), it will simplify my automation to a greater extent. Though this is not required and it seems a bit of a violation of fluid interface design, but I'm still looking forward to such a feature.

**Comment by phantamanta44** [comment]
probably not. you're right in that it defeats the purpose of fluid interfaces, but on top of that, i would have to do more hacking into ME interface code which i would really rather avoid

**Comment by Yefancy** [comment]
All right, I agree with you. BTW, have you considered creating a new interface (eg. combination of me interfaces and fluid interfaces) but not hook in ae source. or do you mind pr and merge from me, if i implement this new interface?
